### ISSUE TITLE
PHP Firebird WIN1252 x UTF8

### ISSUE THREAD

**Issue by elvispdosreis** [FirebirdSQL/php-firebird#1] opened 2020-05-07 14:30 UTC
Dynamic SQL Error SQL error code = -303 Malformed string

I have a problem with php and firebird, where I have a database in firebird 2.5 with the charset WIN1252, and I have php making a connection through the interbase extension where the utf8 charset is defined to do the data transliteration between WIN1252 and UTF8, however when there is a parameter equal to null of error -303 in sql.
However testing by ibexpert does not give error.

```
select
from atividade a
inner join codigo_servicos c on c.cservcod = a.cservcod
where a.ativnome collate win_ptbr like '%limpe%'
      or c.cservcod = null
order by a.ativnome asc
```

**Comment by MartinKoeditz** [comment] 2020-05-07 14:34
Hi,

please show me the DDL structure of your table (CREATE statement) and some data. Then I will be able to reproduce your problem.

Regards,
Martin

**Comment by elvispdosreis** [comment] 2020-05-13 09:34
I'll set up an example of how to simulate

Em qui., 7 de mai. de 2020 às 11:35, Martin Köditz <notifications@github.com>
escreveu:

**Comment by MartinKoeditz** [comment] 2020-09-24 10:03
Hi,

is this still a problem or could you fix it? Then I will close this issue.

Regards
Martin

**Comment by MartinKoeditz** [comment] 2020-12-09 08:10
Seems to be no PHP related problem. I will close this issue. If there is still a problem, just open it again.

**Closed by MartinKoeditz** 2020-12-09 08:10 UTC
